# .scrutinizer.yml
checks:
    php:
        code_rating: true
        duplication: true
filter:
  excluded_paths:
    - tests/*
build:
  dependencies:
    before:
      - composer install --prefer-source --no-progress
